"""add winner probability engine

Revision ID: 0016_add_winner_probability_engine
Revises: 0015_harden_job_leases
Create Date: 2026-07-31 00:00:00.000000
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0016_add_winner_probability_engine"
down_revision: str | None = "0015_harden_job_leases"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


OWPE_TABLE_NAMES = (
    "winner_prediction_episodes",
    "winner_outcome_definitions",
    "winner_prediction_snapshots",
    "winner_forward_outcomes",
    "winner_target_stop_outcomes",
    "winner_cohort_definitions",
    "winner_cohort_statistics",
    "winner_evidence_manifests",
    "winner_model_versions",
    "winner_probability_estimates",
    "winner_estimate_evidence_members",
    "winner_calibration_bins",
    "winner_drift_metrics",
    "winner_processing_runs",
    "winner_model_training_runs",
    "winner_model_lifecycle_events",
    "winner_similarity_links",
)


CREATE_TABLE_SQL = (
    r"""CREATE TABLE winner_prediction_episodes (
	id BIGSERIAL NOT NULL,
	ticker TEXT NOT NULL,
	setup_family TEXT,
	trigger_state TEXT,
	episode_key TEXT NOT NULL,
	starts_on DATE NOT NULL,
	ends_on DATE,
	cooldown_sessions INTEGER NOT NULL,
	dependency_group_hash TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_prediction_episodes_key UNIQUE (episode_key)
);""",
    r"""CREATE INDEX idx_winner_prediction_episodes_group ON winner_prediction_episodes (dependency_group_hash);""",
    r"""CREATE INDEX idx_winner_prediction_episodes_ticker_dates ON winner_prediction_episodes (ticker, starts_on, ends_on);""",
    r"""CREATE TABLE winner_outcome_definitions (
	id BIGSERIAL NOT NULL,
	definition_id TEXT NOT NULL,
	label TEXT NOT NULL,
	entry_model TEXT NOT NULL,
	horizon_sessions INTEGER NOT NULL,
	target_pct NUMERIC(10, 4),
	stop_pct NUMERIC(10, 4),
	same_bar_conflict_policy TEXT,
	calculation_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	is_primary BOOLEAN DEFAULT 'false' NOT NULL,
	is_active BOOLEAN DEFAULT 'true' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	retired_at TIMESTAMP WITH TIME ZONE,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_outcome_definitions_definition_version UNIQUE (definition_id, calculation_version)
);""",
    r"""CREATE UNIQUE INDEX idx_winner_outcome_definitions_active ON winner_outcome_definitions (definition_id) WHERE is_active;""",
    r"""CREATE INDEX idx_winner_outcome_definitions_entry_model ON winner_outcome_definitions (entry_model);""",
    r"""CREATE TABLE winner_prediction_snapshots (
	id BIGSERIAL NOT NULL,
	run_id BIGINT NOT NULL,
	raw_row_id BIGINT,
	combined_result_id BIGINT,
	ranking_result_id BIGINT,
	market_regime_snapshot_id BIGINT,
	sector_rotation_snapshot_id BIGINT,
	episode_id BIGINT,
	ticker TEXT NOT NULL,
	prediction_as_of_date DATE NOT NULL,
	source_data_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	captured_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	planned_entry_session DATE,
	entry_schedule_status TEXT NOT NULL,
	entry_data_status TEXT NOT NULL,
	eligibility_status TEXT NOT NULL,
	exclusion_reason TEXT,
	setup_family TEXT,
	setup_classification TEXT,
	ranking_profile TEXT,
	fundamental_score NUMERIC(10, 4),
	technical_score NUMERIC(10, 4),
	combined_score NUMERIC(10, 4),
	market_regime TEXT,
	market_risk_state TEXT,
	sector_state TEXT,
	sector_rank INTEGER,
	suggested_target_pct NUMERIC(10, 4),
	suggested_stop_pct NUMERIC(10, 4),
	reward_risk NUMERIC(10, 4),
	upcoming_earnings_date DATE,
	days_until_earnings INTEGER,
	earnings_risk_level TEXT,
	technical_data_quality TEXT,
	fundamental_coverage NUMERIC(10, 4),
	universe_provenance TEXT,
	screener_provenance TEXT,
	feature_schema_version TEXT NOT NULL,
	feature_vector_hash TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	calculation_version TEXT NOT NULL,
	revision INTEGER DEFAULT '1' NOT NULL,
	superseded_at TIMESTAMP WITH TIME ZONE,
	feature_json JSONB NOT NULL,
	source_ids_json JSONB DEFAULT '{}' NOT NULL,
	warning_flags_json JSONB DEFAULT '[]' NOT NULL,
	lineage_json JSONB DEFAULT '{}' NOT NULL,
	reconstruction_method TEXT,
	retention_class TEXT DEFAULT 'permanent' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_prediction_snapshots_natural_revision UNIQUE (run_id, ticker, prediction_as_of_date, feature_schema_version, revision),
	FOREIGN KEY(run_id) REFERENCES upload_runs (id) ON DELETE CASCADE,
	FOREIGN KEY(raw_row_id) REFERENCES raw_company_rows (id),
	FOREIGN KEY(combined_result_id) REFERENCES combined_results (id),
	FOREIGN KEY(ranking_result_id) REFERENCES ranking_results (id),
	FOREIGN KEY(market_regime_snapshot_id) REFERENCES market_regime_snapshots (id),
	FOREIGN KEY(sector_rotation_snapshot_id) REFERENCES sector_rotation_snapshots (id),
	FOREIGN KEY(episode_id) REFERENCES winner_prediction_episodes (id)
);""",
    r"""CREATE UNIQUE INDEX idx_winner_prediction_snapshots_active_revision ON winner_prediction_snapshots (run_id, ticker, prediction_as_of_date) WHERE superseded_at IS NULL;""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_earnings_quality ON winner_prediction_snapshots (earnings_risk_level, technical_data_quality);""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_eligibility ON winner_prediction_snapshots (eligibility_status);""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_profile ON winner_prediction_snapshots (ranking_profile);""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_regime_sector ON winner_prediction_snapshots (market_risk_state, sector_state);""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_run_ticker ON winner_prediction_snapshots (run_id, ticker);""",
    r"""CREATE INDEX idx_winner_prediction_snapshots_ticker_as_of ON winner_prediction_snapshots (ticker, prediction_as_of_date);""",
    r"""CREATE TABLE winner_forward_outcomes (
	id BIGSERIAL NOT NULL,
	prediction_id BIGINT NOT NULL,
	entry_model TEXT NOT NULL,
	horizon_sessions INTEGER NOT NULL,
	entry_session DATE,
	due_session DATE,
	status TEXT NOT NULL,
	revision INTEGER DEFAULT '1' NOT NULL,
	is_current_revision BOOLEAN DEFAULT 'true' NOT NULL,
	entry_price NUMERIC(18, 6),
	exit_price NUMERIC(18, 6),
	close_return_pct NUMERIC(12, 6),
	spy_return_pct NUMERIC(12, 6),
	excess_spy_return_pct NUMERIC(12, 6),
	sector_return_pct NUMERIC(12, 6),
	excess_sector_return_pct NUMERIC(12, 6),
	mfe_pct NUMERIC(12, 6),
	mae_pct NUMERIC(12, 6),
	sessions_to_mfe INTEGER,
	sessions_to_mae INTEGER,
	positive_return BOOLEAN,
	beat_spy BOOLEAN,
	beat_sector BOOLEAN,
	source_bar_lineage_hash TEXT,
	source_revision_cutoff_at TIMESTAMP WITH TIME ZONE,
	matured_at TIMESTAMP WITH TIME ZONE,
	superseded_at TIMESTAMP WITH TIME ZONE,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_forward_outcomes_prediction_entry_horizon_revision UNIQUE (prediction_id, entry_model, horizon_sessions, revision),
	FOREIGN KEY(prediction_id) REFERENCES winner_prediction_snapshots (id) ON DELETE CASCADE
);""",
    r"""CREATE INDEX idx_winner_forward_outcomes_bar_lineage_current ON winner_forward_outcomes (source_bar_lineage_hash, is_current_revision);""",
    r"""CREATE UNIQUE INDEX idx_winner_forward_outcomes_current_revision ON winner_forward_outcomes (prediction_id, entry_model, horizon_sessions) WHERE is_current_revision;""",
    r"""CREATE INDEX idx_winner_forward_outcomes_prediction_entry_horizon ON winner_forward_outcomes (prediction_id, entry_model, horizon_sessions);""",
    r"""CREATE INDEX idx_winner_forward_outcomes_status_due ON winner_forward_outcomes (status, due_session);""",
    r"""CREATE TABLE winner_target_stop_outcomes (
	id BIGSERIAL NOT NULL,
	prediction_id BIGINT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	forward_outcome_id BIGINT,
	entry_model TEXT NOT NULL,
	horizon_sessions INTEGER NOT NULL,
	status TEXT NOT NULL,
	revision INTEGER DEFAULT '1' NOT NULL,
	is_current_revision BOOLEAN DEFAULT 'true' NOT NULL,
	target_pct NUMERIC(10, 4) NOT NULL,
	stop_pct NUMERIC(10, 4) NOT NULL,
	target_hit BOOLEAN,
	stop_hit BOOLEAN,
	first_event TEXT,
	event_session DATE,
	same_bar_conflict BOOLEAN DEFAULT 'false' NOT NULL,
	primary_winner BOOLEAN,
	optimistic_winner BOOLEAN,
	conservative_winner BOOLEAN,
	source_bar_lineage_hash TEXT,
	evaluated_at TIMESTAMP WITH TIME ZONE,
	superseded_at TIMESTAMP WITH TIME ZONE,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_target_stop_outcomes_prediction_definition_revision UNIQUE (prediction_id, outcome_definition_id, revision),
	FOREIGN KEY(prediction_id) REFERENCES winner_prediction_snapshots (id) ON DELETE CASCADE,
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id),
	FOREIGN KEY(forward_outcome_id) REFERENCES winner_forward_outcomes (id)
);""",
    r"""CREATE UNIQUE INDEX idx_winner_target_stop_outcomes_current_revision ON winner_target_stop_outcomes (prediction_id, outcome_definition_id) WHERE is_current_revision;""",
    r"""CREATE INDEX idx_winner_target_stop_outcomes_prediction_definition ON winner_target_stop_outcomes (prediction_id, outcome_definition_id);""",
    r"""CREATE INDEX idx_winner_target_stop_outcomes_status ON winner_target_stop_outcomes (status);""",
    r"""CREATE TABLE winner_cohort_definitions (
	id BIGSERIAL NOT NULL,
	cohort_key TEXT NOT NULL,
	level TEXT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	entry_model TEXT NOT NULL,
	dimensions_json JSONB NOT NULL,
	feature_schema_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	source_version TEXT NOT NULL,
	status TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	retired_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_cohort_definitions_key_outcome_version UNIQUE (cohort_key, outcome_definition_id, source_version),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_cohort_definitions_level ON winner_cohort_definitions (level);""",
    r"""CREATE INDEX idx_winner_cohort_definitions_status ON winner_cohort_definitions (status);""",
    r"""CREATE TABLE winner_cohort_statistics (
	id BIGSERIAL NOT NULL,
	cohort_definition_id BIGINT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	statistic_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
	training_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	sample_n INTEGER NOT NULL,
	effective_n NUMERIC(18, 6) NOT NULL,
	wins NUMERIC(18, 6) NOT NULL,
	raw_rate NUMERIC(12, 6),
	posterior_probability NUMERIC(12, 6),
	lower_bound NUMERIC(12, 6),
	upper_bound NUMERIC(12, 6),
	median_return_pct NUMERIC(12, 6),
	median_mfe_pct NUMERIC(12, 6),
	median_mae_pct NUMERIC(12, 6),
	evidence_grade TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	evidence_manifest_hash TEXT,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_cohort_statistics_definition_cutoff UNIQUE (cohort_definition_id, outcome_definition_id, training_cutoff_at),
	FOREIGN KEY(cohort_definition_id) REFERENCES winner_cohort_definitions (id) ON DELETE CASCADE,
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_cohort_statistics_cutoff ON winner_cohort_statistics (training_cutoff_at);""",
    r"""CREATE INDEX idx_winner_cohort_statistics_grade_n ON winner_cohort_statistics (evidence_grade, effective_n);""",
    r"""CREATE TABLE winner_evidence_manifests (
	id BIGSERIAL NOT NULL,
	manifest_hash TEXT NOT NULL,
	hash_algorithm TEXT NOT NULL,
	content_encoding TEXT NOT NULL,
	member_count INTEGER NOT NULL,
	compressed_size_bytes BIGINT,
	payload_json JSONB,
	artifact_path TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_evidence_manifests_hash UNIQUE (manifest_hash)
);""",
    r"""CREATE INDEX idx_winner_evidence_manifests_created_at ON winner_evidence_manifests (created_at);""",
    r"""CREATE TABLE winner_model_versions (
	id BIGSERIAL NOT NULL,
	model_key TEXT NOT NULL,
	algorithm TEXT NOT NULL,
	status TEXT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	entry_model TEXT NOT NULL,
	feature_schema_version TEXT NOT NULL,
	calculation_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	training_window_start DATE,
	training_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	hyperparameters_json JSONB DEFAULT '{}' NOT NULL,
	metrics_json JSONB DEFAULT '{}' NOT NULL,
	preprocessing_json JSONB DEFAULT '{}' NOT NULL,
	calibration_json JSONB DEFAULT '{}' NOT NULL,
	artifact_schema_version TEXT NOT NULL,
	artifact_format TEXT NOT NULL,
	artifact_path TEXT,
	artifact_hash TEXT NOT NULL,
	artifact_size_bytes BIGINT,
	dependency_versions_json JSONB DEFAULT '{}' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	activated_at TIMESTAMP WITH TIME ZONE,
	retired_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_model_versions_model_key UNIQUE (model_key),
	CONSTRAINT ck_winner_model_versions_artifact_hash CHECK (artifact_hash <> ''),
	CONSTRAINT ck_winner_model_versions_schema_version CHECK (artifact_schema_version <> ''),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_model_versions_outcome_status ON winner_model_versions (outcome_definition_id, status);""",
    r"""CREATE INDEX idx_winner_model_versions_status ON winner_model_versions (status);""",
    r"""CREATE TABLE winner_probability_estimates (
	id BIGSERIAL NOT NULL,
	prediction_id BIGINT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	estimate_kind TEXT NOT NULL,
	source TEXT NOT NULL,
	source_version TEXT NOT NULL,
	cohort_definition_id BIGINT,
	model_version_id BIGINT,
	evidence_manifest_id BIGINT,
	training_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	point_probability NUMERIC(12, 6),
	lower_bound NUMERIC(12, 6),
	upper_bound NUMERIC(12, 6),
	interval_width NUMERIC(12, 6),
	sample_n INTEGER,
	effective_n NUMERIC(18, 6),
	evidence_grade TEXT NOT NULL,
	insufficient_reasons_json JSONB DEFAULT '[]' NOT NULL,
	expected_return_pct NUMERIC(12, 6),
	median_return_pct NUMERIC(12, 6),
	median_mfe_pct NUMERIC(12, 6),
	median_mae_pct NUMERIC(12, 6),
	target_first_rate NUMERIC(12, 6),
	config_hash TEXT NOT NULL,
	feature_schema_version TEXT NOT NULL,
	evidence_manifest_hash TEXT,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_probability_estimates_identity UNIQUE (prediction_id, outcome_definition_id, estimate_kind, source_version, training_cutoff_at),
	FOREIGN KEY(prediction_id) REFERENCES winner_prediction_snapshots (id) ON DELETE CASCADE,
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id),
	FOREIGN KEY(cohort_definition_id) REFERENCES winner_cohort_definitions (id),
	FOREIGN KEY(model_version_id) REFERENCES winner_model_versions (id),
	FOREIGN KEY(evidence_manifest_id) REFERENCES winner_evidence_manifests (id)
);""",
    r"""CREATE INDEX idx_winner_probability_estimates_grade_n ON winner_probability_estimates (evidence_grade, effective_n);""",
    r"""CREATE INDEX idx_winner_probability_estimates_lower_bound ON winner_probability_estimates (lower_bound);""",
    r"""CREATE INDEX idx_winner_probability_estimates_model_created ON winner_probability_estimates (model_version_id, created_at);""",
    r"""CREATE INDEX idx_winner_probability_estimates_prediction_outcome_kind ON winner_probability_estimates (prediction_id, outcome_definition_id, estimate_kind);""",
    r"""CREATE INDEX idx_winner_probability_estimates_probability ON winner_probability_estimates (point_probability);""",
    r"""CREATE TABLE winner_estimate_evidence_members (
	id BIGSERIAL NOT NULL,
	estimate_id BIGINT NOT NULL,
	prediction_id BIGINT NOT NULL,
	outcome_id BIGINT NOT NULL,
	outcome_revision INTEGER NOT NULL,
	episode_id BIGINT,
	inclusion_weight NUMERIC(18, 8) DEFAULT '1' NOT NULL,
	included_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
	inclusion_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_estimate_evidence_members_estimate_outcome_revision UNIQUE (estimate_id, outcome_id, outcome_revision),
	FOREIGN KEY(estimate_id) REFERENCES winner_probability_estimates (id) ON DELETE CASCADE,
	FOREIGN KEY(prediction_id) REFERENCES winner_prediction_snapshots (id),
	FOREIGN KEY(outcome_id) REFERENCES winner_forward_outcomes (id),
	FOREIGN KEY(episode_id) REFERENCES winner_prediction_episodes (id)
);""",
    r"""CREATE INDEX idx_winner_estimate_evidence_members_estimate_episode ON winner_estimate_evidence_members (estimate_id, episode_id);""",
    r"""CREATE INDEX idx_winner_estimate_evidence_members_estimate_outcome ON winner_estimate_evidence_members (estimate_id, outcome_id);""",
    r"""CREATE INDEX idx_winner_estimate_evidence_members_prediction_asof ON winner_estimate_evidence_members (prediction_id, included_as_of);""",
    r"""CREATE TABLE winner_calibration_bins (
	id BIGSERIAL NOT NULL,
	model_version_id BIGINT,
	outcome_definition_id BIGINT NOT NULL,
	estimate_kind TEXT NOT NULL,
	bin_floor NUMERIC(12, 6) NOT NULL,
	bin_ceiling NUMERIC(12, 6) NOT NULL,
	sample_n INTEGER NOT NULL,
	effective_n NUMERIC(18, 6),
	mean_prediction NUMERIC(12, 6),
	observed_rate NUMERIC(12, 6),
	lower_bound NUMERIC(12, 6),
	upper_bound NUMERIC(12, 6),
	error NUMERIC(12, 6),
	calculated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	segment_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(model_version_id) REFERENCES winner_model_versions (id),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_calibration_bins_model ON winner_calibration_bins (model_version_id);""",
    r"""CREATE INDEX idx_winner_calibration_bins_outcome_kind ON winner_calibration_bins (outcome_definition_id, estimate_kind);""",
    r"""CREATE TABLE winner_drift_metrics (
	id BIGSERIAL NOT NULL,
	model_version_id BIGINT,
	outcome_definition_id BIGINT NOT NULL,
	as_of_date DATE NOT NULL,
	metric_name TEXT NOT NULL,
	metric_value NUMERIC(18, 8),
	threshold_value NUMERIC(18, 8),
	breached BOOLEAN DEFAULT 'false' NOT NULL,
	sample_n INTEGER,
	comparison_window TEXT NOT NULL,
	segment_json JSONB DEFAULT '{}' NOT NULL,
	sufficient_sample BOOLEAN DEFAULT 'false' NOT NULL,
	calculated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_drift_metrics_identity UNIQUE (outcome_definition_id, as_of_date, metric_name, comparison_window),
	FOREIGN KEY(model_version_id) REFERENCES winner_model_versions (id),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_drift_metrics_as_of ON winner_drift_metrics (as_of_date);""",
    r"""CREATE INDEX idx_winner_drift_metrics_breached ON winner_drift_metrics (breached);""",
    r"""CREATE TABLE winner_processing_runs (
	id BIGSERIAL NOT NULL,
	background_job_id BIGINT,
	run_id BIGINT,
	process_type TEXT NOT NULL,
	status TEXT NOT NULL,
	config_hash TEXT,
	source_cutoff_at TIMESTAMP WITH TIME ZONE,
	started_at TIMESTAMP WITH TIME ZONE,
	completed_at TIMESTAMP WITH TIME ZONE,
	counts_json JSONB DEFAULT '{}' NOT NULL,
	checkpoint_json JSONB DEFAULT '{}' NOT NULL,
	error_message TEXT,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(background_job_id) REFERENCES background_jobs (id),
	FOREIGN KEY(run_id) REFERENCES upload_runs (id)
);""",
    r"""CREATE INDEX idx_winner_processing_runs_job_id ON winner_processing_runs (background_job_id);""",
    r"""CREATE INDEX idx_winner_processing_runs_run_id ON winner_processing_runs (run_id);""",
    r"""CREATE INDEX idx_winner_processing_runs_type_status ON winner_processing_runs (process_type, status);""",
    r"""CREATE TABLE winner_model_training_runs (
	id BIGSERIAL NOT NULL,
	background_job_id BIGINT,
	candidate_model_version_id BIGINT,
	outcome_definition_id BIGINT NOT NULL,
	status TEXT NOT NULL,
	algorithm TEXT NOT NULL,
	feature_schema_version TEXT NOT NULL,
	training_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	fold_plan_json JSONB DEFAULT '{}' NOT NULL,
	preprocessing_json JSONB DEFAULT '{}' NOT NULL,
	metrics_json JSONB DEFAULT '{}' NOT NULL,
	warnings_json JSONB DEFAULT '[]' NOT NULL,
	artifact_hash TEXT,
	started_at TIMESTAMP WITH TIME ZONE,
	completed_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(background_job_id) REFERENCES background_jobs (id),
	FOREIGN KEY(candidate_model_version_id) REFERENCES winner_model_versions (id),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id)
);""",
    r"""CREATE INDEX idx_winner_model_training_runs_candidate ON winner_model_training_runs (candidate_model_version_id);""",
    r"""CREATE INDEX idx_winner_model_training_runs_status ON winner_model_training_runs (status);""",
    r"""CREATE TABLE winner_model_lifecycle_events (
	id BIGSERIAL NOT NULL,
	model_version_id BIGINT NOT NULL,
	event_type TEXT NOT NULL,
	actor TEXT NOT NULL,
	reason TEXT NOT NULL,
	old_status TEXT,
	new_status TEXT,
	replacement_model_version_id BIGINT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(model_version_id) REFERENCES winner_model_versions (id),
	FOREIGN KEY(replacement_model_version_id) REFERENCES winner_model_versions (id)
);""",
    r"""CREATE INDEX idx_winner_model_lifecycle_events_model ON winner_model_lifecycle_events (model_version_id);""",
    r"""CREATE INDEX idx_winner_model_lifecycle_events_type ON winner_model_lifecycle_events (event_type);""",
    r"""CREATE TABLE winner_similarity_links (
	id BIGSERIAL NOT NULL,
	prediction_id BIGINT NOT NULL,
	neighbor_prediction_id BIGINT NOT NULL,
	outcome_definition_id BIGINT NOT NULL,
	outcome_id BIGINT,
	outcome_revision INTEGER,
	rank INTEGER NOT NULL,
	distance NUMERIC(18, 8) NOT NULL,
	similarity_coverage NUMERIC(12, 6) NOT NULL,
	contribution_json JSONB DEFAULT '{}' NOT NULL,
	cache_version TEXT NOT NULL,
	source_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_winner_similarity_links_prediction_definition_cache_rank UNIQUE (prediction_id, outcome_definition_id, cache_version, rank),
	FOREIGN KEY(prediction_id) REFERENCES winner_prediction_snapshots (id) ON DELETE CASCADE,
	FOREIGN KEY(neighbor_prediction_id) REFERENCES winner_prediction_snapshots (id),
	FOREIGN KEY(outcome_definition_id) REFERENCES winner_outcome_definitions (id),
	FOREIGN KEY(outcome_id) REFERENCES winner_forward_outcomes (id)
);""",
    r"""CREATE INDEX idx_winner_similarity_links_neighbor ON winner_similarity_links (neighbor_prediction_id);""",
    r"""CREATE INDEX idx_winner_similarity_links_prediction ON winner_similarity_links (prediction_id);""",
)


def upgrade() -> None:
    op.alter_column(
        "alembic_version",
        "version_num",
        existing_type=sa.String(length=32),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    for statement in CREATE_TABLE_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("winner_similarity_links")
    op.drop_table("winner_model_lifecycle_events")
    op.drop_table("winner_model_training_runs")
    op.drop_table("winner_processing_runs")
    op.drop_table("winner_drift_metrics")
    op.drop_table("winner_calibration_bins")
    op.drop_table("winner_estimate_evidence_members")
    op.drop_table("winner_probability_estimates")
    op.drop_table("winner_model_versions")
    op.drop_table("winner_evidence_manifests")
    op.drop_table("winner_cohort_statistics")
    op.drop_table("winner_cohort_definitions")
    op.drop_table("winner_target_stop_outcomes")
    op.drop_table("winner_forward_outcomes")
    op.drop_table("winner_prediction_snapshots")
    op.drop_table("winner_outcome_definitions")
    op.drop_table("winner_prediction_episodes")
