"""add ceri tables

Revision ID: 0018_add_ceri_tables
Revises: 0017_create_setup_lifecycle_tables
Create Date: 2026-08-01 00:00:00.000000
"""

# ruff: noqa: E501

from collections.abc import Sequence

from alembic import op

revision: str = "0018_add_ceri_tables"
down_revision: str | None = "0017_create_setup_lifecycle_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


CERI_TABLE_NAMES = (
    "ceri_companies",
    "ceri_company_aliases",
    "ceri_ingestion_runs",
    "ceri_processing_runs",
    "ceri_source_records",
    "ceri_estimate_snapshots",
    "ceri_earnings_actuals",
    "ceri_guidance_events",
    "ceri_catalyst_events",
    "ceri_catalyst_event_revisions",
    "ceri_catalyst_sources",
    "ceri_revision_features",
    "ceri_score_snapshots",
    "ceri_change_events",
    "ceri_manual_reviews",
    "ceri_alert_rules",
    "ceri_alert_events",
    "ceri_purge_audits",
)


CREATE_TABLE_SQL = (
    r"""CREATE TABLE ceri_companies (
	id BIGSERIAL NOT NULL,
	ticker VARCHAR(32) NOT NULL,
	exchange VARCHAR(32),
	company_name TEXT,
	cik VARCHAR(32),
	current_provider_ids_json JSONB,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_companies_ticker_exchange UNIQUE (ticker, exchange)
);""",
    r"""CREATE INDEX ix_ceri_companies_cik ON ceri_companies (cik);""",
    r"""CREATE TABLE ceri_company_aliases (
	id BIGSERIAL NOT NULL,
	company_id BIGINT NOT NULL,
	provider VARCHAR(64) NOT NULL,
	alias_type VARCHAR(64) NOT NULL,
	alias_value VARCHAR(128) NOT NULL,
	exchange VARCHAR(32),
	valid_from DATE,
	valid_to DATE,
	source TEXT,
	confidence VARCHAR(32) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_company_alias_validity UNIQUE (provider, alias_type, alias_value, valid_from, valid_to),
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE CASCADE
);""",
    r"""CREATE INDEX ix_ceri_company_aliases_company ON ceri_company_aliases (company_id);""",
    r"""CREATE INDEX ix_ceri_company_aliases_lookup ON ceri_company_aliases (provider, alias_type, alias_value);""",
    r"""CREATE TABLE ceri_ingestion_runs (
	id BIGSERIAL NOT NULL,
	provider VARCHAR(64) NOT NULL,
	provider_terms_version TEXT,
	dataset VARCHAR(64) NOT NULL,
	scope_json JSONB,
	status VARCHAR(32) NOT NULL,
	request_key TEXT NOT NULL,
	config_version TEXT,
	config_hash TEXT,
	quota_state_json JSONB,
	retry_count INTEGER NOT NULL,
	checkpoint_json JSONB,
	requested_count INTEGER NOT NULL,
	fetched_count INTEGER NOT NULL,
	inserted_count INTEGER NOT NULL,
	deduplicated_count INTEGER NOT NULL,
	corrected_count INTEGER NOT NULL,
	quarantined_count INTEGER NOT NULL,
	failed_count INTEGER NOT NULL,
	warning_count INTEGER NOT NULL,
	errors_json JSONB,
	warnings_json JSONB,
	duration_ms INTEGER,
	started_at TIMESTAMP WITH TIME ZONE,
	completed_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_ingestion_runs_request_key UNIQUE (request_key)
);""",
    r"""CREATE INDEX ix_ceri_ingestion_runs_provider_dataset_status ON ceri_ingestion_runs (provider, dataset, status);""",
    r"""CREATE TABLE ceri_processing_runs (
	id BIGSERIAL NOT NULL,
	job_type VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL,
	deterministic_request_key TEXT NOT NULL,
	scope_json JSONB,
	config_version TEXT,
	config_hash TEXT,
	cutoff_at TIMESTAMP WITH TIME ZONE,
	actor TEXT,
	retry_count INTEGER NOT NULL,
	read_count INTEGER NOT NULL,
	normalized_count INTEGER NOT NULL,
	feature_count INTEGER NOT NULL,
	score_snapshot_count INTEGER NOT NULL,
	change_event_count INTEGER NOT NULL,
	alert_event_count INTEGER NOT NULL,
	warning_count INTEGER NOT NULL,
	failed_count INTEGER NOT NULL,
	counts_json JSONB,
	checkpoint_json JSONB,
	errors_json JSONB,
	heartbeat_at TIMESTAMP WITH TIME ZONE,
	execution_token TEXT,
	duration_ms INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	started_at TIMESTAMP WITH TIME ZONE,
	completed_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_processing_runs_request_key UNIQUE (deterministic_request_key)
);""",
    r"""CREATE INDEX ix_ceri_processing_runs_heartbeat ON ceri_processing_runs (heartbeat_at);""",
    r"""CREATE INDEX ix_ceri_processing_runs_status_checkpoint ON ceri_processing_runs (status, job_type);""",
    r"""CREATE TABLE ceri_source_records (
	id BIGSERIAL NOT NULL,
	ingestion_run_id BIGINT,
	provider VARCHAR(64) NOT NULL,
	provider_terms_version TEXT,
	dataset VARCHAR(64) NOT NULL,
	provider_record_id TEXT NOT NULL,
	company_hint_json JSONB,
	published_at TIMESTAMP WITH TIME ZONE,
	observed_at TIMESTAMP WITH TIME ZONE,
	ingested_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	source_url TEXT,
	source_reference TEXT,
	raw_json JSONB,
	restricted_normalized_json JSONB,
	content_hash VARCHAR(128) NOT NULL,
	idempotency_key TEXT NOT NULL,
	export_policy VARCHAR(32) NOT NULL,
	provider_retention_deadline DATE,
	supersedes_id BIGINT,
	correction_type VARCHAR(64),
	quarantine_reason TEXT,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_source_records_provider_record UNIQUE (provider, dataset, provider_record_id),
	CONSTRAINT uq_ceri_source_records_idempotency UNIQUE (idempotency_key),
	FOREIGN KEY(ingestion_run_id) REFERENCES ceri_ingestion_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(supersedes_id) REFERENCES ceri_source_records (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_source_records_content_hash ON ceri_source_records (content_hash);""",
    r"""CREATE INDEX ix_ceri_source_records_dataset_published ON ceri_source_records (dataset, published_at);""",
    r"""CREATE INDEX ix_ceri_source_records_quarantine ON ceri_source_records (quarantine_reason);""",
    r"""CREATE TABLE ceri_estimate_snapshots (
	id BIGSERIAL NOT NULL,
	source_record_id BIGINT NOT NULL,
	company_id BIGINT NOT NULL,
	metric VARCHAR(64) NOT NULL,
	fiscal_period_end DATE NOT NULL,
	period_type VARCHAR(64) NOT NULL,
	fiscal_year INTEGER,
	fiscal_quarter INTEGER,
	consensus NUMERIC(20, 6),
	high NUMERIC(20, 6),
	low NUMERIC(20, 6),
	analyst_count INTEGER,
	upward_count INTEGER,
	downward_count INTEGER,
	source_currency VARCHAR(16),
	source_scale NUMERIC(20, 6),
	canonical_currency VARCHAR(16),
	canonical_scale NUMERIC(20, 6),
	conversion_rate NUMERIC(20, 10),
	conversion_source_record_id BIGINT,
	conversion_effective_at TIMESTAMP WITH TIME ZONE,
	effective_at TIMESTAMP WITH TIME ZONE,
	effective_session DATE,
	canonical_observation_key TEXT NOT NULL,
	original_fields_json JSONB,
	quality_flags_json JSONB,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_estimate_snapshots_observation UNIQUE (company_id, metric, period_type, fiscal_period_end, canonical_observation_key),
	CONSTRAINT ck_ceri_estimates_analysts_nonnegative CHECK (analyst_count IS NULL OR analyst_count >= 0),
	FOREIGN KEY(source_record_id) REFERENCES ceri_source_records (id) ON DELETE RESTRICT,
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT,
	FOREIGN KEY(conversion_source_record_id) REFERENCES ceri_source_records (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_estimate_snapshots_company_metric_effective ON ceri_estimate_snapshots (company_id, metric, effective_at);""",
    r"""CREATE INDEX ix_ceri_estimate_snapshots_effective_session ON ceri_estimate_snapshots (effective_session);""",
    r"""CREATE TABLE ceri_earnings_actuals (
	id BIGSERIAL NOT NULL,
	source_record_id BIGINT NOT NULL,
	company_id BIGINT NOT NULL,
	metric VARCHAR(64) NOT NULL,
	period_type VARCHAR(64) NOT NULL,
	fiscal_period_end DATE NOT NULL,
	report_at TIMESTAMP WITH TIME ZONE,
	report_session DATE,
	actual_value NUMERIC(20, 6),
	consensus_snapshot_id BIGINT,
	consensus_selection_reason TEXT,
	surprise_absolute NUMERIC(20, 6),
	surprise_pct NUMERIC(20, 6),
	quality_warnings_json JSONB,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_earnings_actuals_source_metric_period UNIQUE (source_record_id, metric, period_type, fiscal_period_end),
	FOREIGN KEY(source_record_id) REFERENCES ceri_source_records (id) ON DELETE RESTRICT,
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT,
	FOREIGN KEY(consensus_snapshot_id) REFERENCES ceri_estimate_snapshots (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_earnings_actuals_company_report ON ceri_earnings_actuals (company_id, report_session);""",
    r"""CREATE TABLE ceri_guidance_events (
	id BIGSERIAL NOT NULL,
	source_record_id BIGINT NOT NULL,
	company_id BIGINT NOT NULL,
	action VARCHAR(64) NOT NULL,
	metric VARCHAR(64),
	period_type VARCHAR(64),
	period_label TEXT,
	low_value NUMERIC(20, 6),
	high_value NUMERIC(20, 6),
	comparison_basis TEXT,
	confidence VARCHAR(32) NOT NULL,
	effective_at TIMESTAMP WITH TIME ZONE,
	effective_session DATE,
	supersedes_id BIGINT,
	quality_warnings_json JSONB,
	PRIMARY KEY (id),
	FOREIGN KEY(source_record_id) REFERENCES ceri_source_records (id) ON DELETE RESTRICT,
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT,
	FOREIGN KEY(supersedes_id) REFERENCES ceri_guidance_events (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_guidance_events_action ON ceri_guidance_events (action);""",
    r"""CREATE INDEX ix_ceri_guidance_events_company_effective ON ceri_guidance_events (company_id, effective_session);""",
    r"""CREATE TABLE ceri_catalyst_events (
	id BIGSERIAL NOT NULL,
	company_id BIGINT NOT NULL,
	category VARCHAR(64) NOT NULL,
	subtype VARCHAR(128),
	subject_key TEXT NOT NULL,
	canonical_text TEXT,
	first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	last_updated_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_catalyst_events_cluster UNIQUE (company_id, category, subject_key),
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT
);""",
    r"""CREATE INDEX ix_ceri_catalyst_events_company_category ON ceri_catalyst_events (company_id, category);""",
    r"""CREATE TABLE ceri_catalyst_event_revisions (
	id BIGSERIAL NOT NULL,
	catalyst_event_id BIGINT NOT NULL,
	source_record_id BIGINT,
	prior_revision_id BIGINT,
	outcome_revision_id BIGINT,
	revision_number INTEGER NOT NULL,
	is_current BOOLEAN NOT NULL,
	announced_at TIMESTAMP WITH TIME ZONE,
	expected_date DATE,
	effective_session DATE,
	status VARCHAR(64) NOT NULL,
	direction VARCHAR(64) NOT NULL,
	materiality FLOAT,
	date_confidence VARCHAR(64),
	source_confidence VARCHAR(64),
	operational_values_json JSONB,
	conflict_flags_json JSONB,
	review_state VARCHAR(64),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_catalyst_event_revision_number UNIQUE (catalyst_event_id, revision_number),
	FOREIGN KEY(catalyst_event_id) REFERENCES ceri_catalyst_events (id) ON DELETE CASCADE,
	FOREIGN KEY(source_record_id) REFERENCES ceri_source_records (id) ON DELETE SET NULL,
	FOREIGN KEY(prior_revision_id) REFERENCES ceri_catalyst_event_revisions (id) ON DELETE SET NULL,
	FOREIGN KEY(outcome_revision_id) REFERENCES ceri_catalyst_event_revisions (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_catalyst_event_revisions_status ON ceri_catalyst_event_revisions (status);""",
    r"""CREATE UNIQUE INDEX uq_ceri_catalyst_event_current_revision ON ceri_catalyst_event_revisions (catalyst_event_id) WHERE is_current = true;""",
    r"""CREATE TABLE ceri_catalyst_sources (
	id BIGSERIAL NOT NULL,
	catalyst_event_id BIGINT NOT NULL,
	catalyst_revision_id BIGINT,
	source_record_id BIGINT NOT NULL,
	source_fields_json JSONB,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_catalyst_sources_event_source UNIQUE (catalyst_event_id, source_record_id),
	FOREIGN KEY(catalyst_event_id) REFERENCES ceri_catalyst_events (id) ON DELETE CASCADE,
	FOREIGN KEY(catalyst_revision_id) REFERENCES ceri_catalyst_event_revisions (id) ON DELETE SET NULL,
	FOREIGN KEY(source_record_id) REFERENCES ceri_source_records (id) ON DELETE RESTRICT
);""",
    r"""CREATE INDEX ix_ceri_catalyst_sources_source ON ceri_catalyst_sources (source_record_id);""",
    r"""CREATE TABLE ceri_revision_features (
	id BIGSERIAL NOT NULL,
	company_id BIGINT NOT NULL,
	metric VARCHAR(64) NOT NULL,
	period_key TEXT NOT NULL,
	as_of_session DATE NOT NULL,
	window_days INTEGER NOT NULL,
	baseline_snapshot_id BIGINT,
	current_snapshot_id BIGINT,
	actual_elapsed_days INTEGER,
	absolute_change NUMERIC(20, 6),
	pct_change NUMERIC(20, 6),
	upward_count INTEGER,
	downward_count INTEGER,
	net_breadth NUMERIC(10, 6),
	dispersion NUMERIC(10, 6),
	acceleration NUMERIC(20, 6),
	revision_confidence_score FLOAT,
	revision_confidence_label VARCHAR(32),
	warnings_json JSONB,
	source_observation_ids_json JSONB,
	provider_selection_reason TEXT,
	unavailable_reason TEXT,
	evidence_hash TEXT,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	calculation_version TEXT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_revision_features_identity UNIQUE (company_id, metric, period_key, as_of_session, window_days, config_hash, calculation_version),
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT,
	FOREIGN KEY(baseline_snapshot_id) REFERENCES ceri_estimate_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(current_snapshot_id) REFERENCES ceri_estimate_snapshots (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_revision_features_company_session ON ceri_revision_features (company_id, as_of_session);""",
    r"""CREATE TABLE ceri_score_snapshots (
	id BIGSERIAL NOT NULL,
	run_id BIGINT,
	source_run_id_text TEXT,
	company_id BIGINT NOT NULL,
	ticker VARCHAR(32) NOT NULL,
	as_of_session DATE NOT NULL,
	cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL,
	opportunity_score FLOAT,
	event_risk_score FLOAT,
	data_confidence VARCHAR(32) NOT NULL,
	coverage_pct FLOAT NOT NULL,
	posture VARCHAR(64) NOT NULL,
	earnings_proximity_risk FLOAT,
	alignment_flags_json JSONB,
	top_positive_contributors_json JSONB,
	top_negative_contributors_json JSONB,
	component_json JSONB,
	reasons_json JSONB,
	warnings_json JSONB,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	calculation_version TEXT NOT NULL,
	evidence_hash TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_score_snapshots_run_company_version UNIQUE (run_id, company_id, config_hash, calculation_version),
	FOREIGN KEY(run_id) REFERENCES upload_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT
);""",
    r"""CREATE INDEX ix_ceri_score_snapshots_confidence ON ceri_score_snapshots (data_confidence);""",
    r"""CREATE INDEX ix_ceri_score_snapshots_run_ticker ON ceri_score_snapshots (run_id, ticker);""",
    r"""CREATE INDEX ix_ceri_score_snapshots_scores ON ceri_score_snapshots (opportunity_score, event_risk_score);""",
    r"""CREATE TABLE ceri_change_events (
	id BIGSERIAL NOT NULL,
	company_id BIGINT NOT NULL,
	from_snapshot_id BIGINT,
	to_snapshot_id BIGINT,
	catalyst_revision_id BIGINT,
	change_type VARCHAR(64) NOT NULL,
	severity VARCHAR(32) NOT NULL,
	delta_json JSONB,
	dedup_key TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_change_events_dedup_key UNIQUE (dedup_key),
	FOREIGN KEY(company_id) REFERENCES ceri_companies (id) ON DELETE RESTRICT,
	FOREIGN KEY(from_snapshot_id) REFERENCES ceri_score_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(to_snapshot_id) REFERENCES ceri_score_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(catalyst_revision_id) REFERENCES ceri_catalyst_event_revisions (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_change_events_company_created ON ceri_change_events (company_id, created_at);""",
    r"""CREATE INDEX ix_ceri_change_events_type ON ceri_change_events (change_type);""",
    r"""CREATE TABLE ceri_manual_reviews (
	id BIGSERIAL NOT NULL,
	target_type VARCHAR(64) NOT NULL,
	target_id BIGINT NOT NULL,
	prior_value_json JSONB,
	new_value_json JSONB,
	reviewer TEXT NOT NULL,
	reason TEXT NOT NULL,
	prior_review_id BIGINT,
	is_current BOOLEAN NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(prior_review_id) REFERENCES ceri_manual_reviews (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_manual_reviews_target ON ceri_manual_reviews (target_type, target_id);""",
    r"""CREATE UNIQUE INDEX uq_ceri_manual_reviews_active_target ON ceri_manual_reviews (target_type, target_id) WHERE is_current = true;""",
    r"""CREATE TABLE ceri_alert_rules (
	id BIGSERIAL NOT NULL,
	rule_id VARCHAR(128) NOT NULL,
	enabled BOOLEAN NOT NULL,
	severity VARCHAR(32) NOT NULL,
	thresholds_json JSONB,
	scope_json JSONB,
	cooldown_sessions INTEGER NOT NULL,
	config_version TEXT NOT NULL,
	source_event_types_json JSONB,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_alert_rules_rule_id UNIQUE (rule_id)
);""",
    r"""CREATE TABLE ceri_alert_events (
	id BIGSERIAL NOT NULL,
	alert_rule_id BIGINT,
	source_change_event_id BIGINT,
	source_catalyst_revision_id BIGINT,
	event_key TEXT NOT NULL,
	ticker VARCHAR(32) NOT NULL,
	severity VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	evidence_json JSONB,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	acknowledged_at TIMESTAMP WITH TIME ZONE,
	dismissed_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_alert_events_event_key UNIQUE (event_key),
	FOREIGN KEY(alert_rule_id) REFERENCES ceri_alert_rules (id) ON DELETE SET NULL,
	FOREIGN KEY(source_change_event_id) REFERENCES ceri_change_events (id) ON DELETE SET NULL,
	FOREIGN KEY(source_catalyst_revision_id) REFERENCES ceri_catalyst_event_revisions (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX ix_ceri_alert_events_status_created ON ceri_alert_events (status, created_at);""",
    r"""CREATE INDEX ix_ceri_alert_events_ticker ON ceri_alert_events (ticker);""",
    r"""CREATE TABLE ceri_purge_audits (
	id BIGSERIAL NOT NULL,
	provider VARCHAR(64) NOT NULL,
	license_scope TEXT NOT NULL,
	preview_manifest_hash TEXT NOT NULL,
	actor TEXT NOT NULL,
	reason TEXT NOT NULL,
	confirmation_token_hash TEXT,
	affected_counts_json JSONB,
	invalidated_derivatives_json JSONB,
	status VARCHAR(32) NOT NULL,
	previewed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	executed_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_ceri_purge_audits_preview_scope UNIQUE (provider, license_scope, preview_manifest_hash)
);""",
    r"""CREATE INDEX ix_ceri_purge_audits_status ON ceri_purge_audits (status);""",
)


def upgrade() -> None:
    for statement in CREATE_TABLE_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("ceri_purge_audits")
    op.drop_table("ceri_alert_events")
    op.drop_table("ceri_alert_rules")
    op.drop_table("ceri_manual_reviews")
    op.drop_table("ceri_change_events")
    op.drop_table("ceri_score_snapshots")
    op.drop_table("ceri_revision_features")
    op.drop_table("ceri_catalyst_sources")
    op.drop_table("ceri_catalyst_event_revisions")
    op.drop_table("ceri_catalyst_events")
    op.drop_table("ceri_guidance_events")
    op.drop_table("ceri_earnings_actuals")
    op.drop_table("ceri_estimate_snapshots")
    op.drop_table("ceri_source_records")
    op.drop_table("ceri_processing_runs")
    op.drop_table("ceri_ingestion_runs")
    op.drop_table("ceri_company_aliases")
    op.drop_table("ceri_companies")
