"""create setup lifecycle tables

Revision ID: 0017_create_setup_lifecycle_tables
Revises: 0016_add_winner_probability_engine
Create Date: 2026-08-01 00:00:00.000000
"""

# ruff: noqa: E501

from collections.abc import Sequence

from alembic import op

revision: str = "0017_create_setup_lifecycle_tables"
down_revision: str | None = "0016_add_winner_probability_engine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SETUP_LIFECYCLE_TABLE_NAMES = (
    "setup_lifecycle_evaluation_runs",
    "setup_signal_snapshots",
    "setup_lifecycle_episodes",
    "setup_lifecycle_events",
    "signal_change_events",
    "signal_alert_rules",
    "signal_alert_events",
    "setup_lifecycle_administrative_audit_events",
)


CREATE_TABLE_SQL = (
    r"""CREATE TABLE setup_lifecycle_evaluation_runs (
	id BIGSERIAL NOT NULL,
	source_run_id BIGINT,
	source_run_id_text TEXT,
	mode VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	current_phase VARCHAR(64),
	engine_version TEXT NOT NULL,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	output_evaluation_version TEXT,
	date_from DATE,
	date_to DATE,
	ticker_scope_json JSONB DEFAULT '[]' NOT NULL,
	requested_config_json JSONB DEFAULT '{}' NOT NULL,
	dry_run BOOLEAN DEFAULT 'false' NOT NULL,
	requester TEXT,
	source_snapshot_min_id BIGINT,
	source_snapshot_max_id BIGINT,
	read_count INTEGER DEFAULT '0' NOT NULL,
	captured_count INTEGER DEFAULT '0' NOT NULL,
	canonical_count INTEGER DEFAULT '0' NOT NULL,
	changed_count INTEGER DEFAULT '0' NOT NULL,
	transitioned_count INTEGER DEFAULT '0' NOT NULL,
	alerted_count INTEGER DEFAULT '0' NOT NULL,
	skipped_count INTEGER DEFAULT '0' NOT NULL,
	warning_count INTEGER DEFAULT '0' NOT NULL,
	failed_count INTEGER DEFAULT '0' NOT NULL,
	counts_json JSONB DEFAULT '{}' NOT NULL,
	error_summary_json JSONB DEFAULT '{}' NOT NULL,
	audit_json JSONB DEFAULT '{}' NOT NULL,
	started_at TIMESTAMP WITH TIME ZONE,
	heartbeat_at TIMESTAMP WITH TIME ZONE,
	last_heartbeat_at TIMESTAMP WITH TIME ZONE,
	completed_at TIMESTAMP WITH TIME ZONE,
	duration_ms INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(source_run_id) REFERENCES upload_runs (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_setup_lifecycle_eval_runs_date_range ON setup_lifecycle_evaluation_runs (date_from, date_to);""",
    r"""CREATE INDEX idx_setup_lifecycle_eval_runs_mode_status ON setup_lifecycle_evaluation_runs (mode, status);""",
    r"""CREATE INDEX idx_setup_lifecycle_eval_runs_source_run ON setup_lifecycle_evaluation_runs (source_run_id);""",
    r"""CREATE INDEX idx_setup_lifecycle_eval_runs_status ON setup_lifecycle_evaluation_runs (status, created_at);""",
    r"""CREATE INDEX idx_setup_lifecycle_eval_runs_version ON setup_lifecycle_evaluation_runs (output_evaluation_version);""",
    r"""CREATE TABLE setup_signal_snapshots (
	id BIGSERIAL NOT NULL,
	evaluation_run_id BIGINT,
	run_id BIGINT,
	source_run_id_text TEXT,
	raw_row_id BIGINT,
	fundamental_score_id BIGINT,
	technical_score_id BIGINT,
	combined_result_id BIGINT,
	ranking_result_id BIGINT,
	market_regime_snapshot_id BIGINT,
	sector_rotation_snapshot_id BIGINT,
	ticker TEXT NOT NULL,
	company_name TEXT,
	sector TEXT,
	timeframe VARCHAR(16) NOT NULL,
	data_as_of_date DATE NOT NULL,
	calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	captured_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	origin_type VARCHAR(32) NOT NULL,
	engine_version TEXT NOT NULL,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	source_data_hash TEXT NOT NULL,
	schema_version TEXT NOT NULL,
	is_canonical BOOLEAN DEFAULT 'false' NOT NULL,
	canonical_reason TEXT,
	canonicalized_at TIMESTAMP WITH TIME ZONE,
	superseded_by_snapshot_id BIGINT,
	primary_setup_family VARCHAR(32),
	primary_phase VARCHAR(64),
	lifecycle_state_candidate VARCHAR(32),
	actionability_candidate VARCHAR(32),
	data_quality_label VARCHAR(32) NOT NULL,
	confidence_score INTEGER,
	confidence_label VARCHAR(32),
	fundamental_score NUMERIC(12, 6),
	dual_score NUMERIC(12, 6),
	trend_score NUMERIC(12, 6),
	momentum_score NUMERIC(12, 6),
	setup_score NUMERIC(12, 6),
	risk_score NUMERIC(12, 6),
	final_score NUMERIC(12, 6),
	profile_score NUMERIC(12, 6),
	technical_classification TEXT,
	stage TEXT,
	pullback_health TEXT,
	action_bias TEXT,
	combined_decision TEXT,
	ranking_profile TEXT,
	close_price NUMERIC(18, 6),
	pivot_price NUMERIC(18, 6),
	trigger_price NUMERIC(18, 6),
	stop_price NUMERIC(18, 6),
	target_price NUMERIC(18, 6),
	distance_to_pivot_pct NUMERIC(12, 6),
	entry_risk_pct NUMERIC(12, 6),
	reward_risk NUMERIC(12, 6),
	close_above_trigger BOOLEAN,
	high_above_trigger BOOLEAN,
	high_price NUMERIC(18, 6),
	technical_confidence VARCHAR(32),
	required_feature_coverage NUMERIC(12, 6),
	freshness_status VARCHAR(32),
	signals_json JSONB DEFAULT '{}' NOT NULL,
	feature_flags_json JSONB DEFAULT '{}' NOT NULL,
	warning_flags_json JSONB DEFAULT '[]' NOT NULL,
	missing_data_json JSONB DEFAULT '{}' NOT NULL,
	source_lineage_json JSONB DEFAULT '{}' NOT NULL,
	diagnostic_high_cross_json JSONB DEFAULT '{}' NOT NULL,
	canonical_decision_json JSONB DEFAULT '{}' NOT NULL,
	debug_json JSONB DEFAULT '{}' NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_setup_signal_snapshots_run_identity UNIQUE (run_id, ticker, timeframe, engine_version, config_hash),
	FOREIGN KEY(evaluation_run_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(run_id) REFERENCES upload_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(raw_row_id) REFERENCES raw_company_rows (id) ON DELETE SET NULL,
	FOREIGN KEY(fundamental_score_id) REFERENCES fundamental_scores (id) ON DELETE SET NULL,
	FOREIGN KEY(technical_score_id) REFERENCES technical_scores (id) ON DELETE SET NULL,
	FOREIGN KEY(combined_result_id) REFERENCES combined_results (id) ON DELETE SET NULL,
	FOREIGN KEY(ranking_result_id) REFERENCES ranking_results (id) ON DELETE SET NULL,
	FOREIGN KEY(market_regime_snapshot_id) REFERENCES market_regime_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(sector_rotation_snapshot_id) REFERENCES sector_rotation_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(superseded_by_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_eval_run ON setup_signal_snapshots (evaluation_run_id);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_family_phase ON setup_signal_snapshots (primary_setup_family, primary_phase);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_quality ON setup_signal_snapshots (data_quality_label);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_run_ticker ON setup_signal_snapshots (run_id, ticker);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_source_hash ON setup_signal_snapshots (source_data_hash);""",
    r"""CREATE INDEX idx_setup_signal_snapshots_ticker_as_of ON setup_signal_snapshots (ticker, data_as_of_date);""",
    r"""CREATE UNIQUE INDEX uq_setup_signal_snapshots_canonical_day ON setup_signal_snapshots (ticker, timeframe, data_as_of_date) WHERE is_canonical;""",
    r"""CREATE TABLE setup_lifecycle_episodes (
	id BIGSERIAL NOT NULL,
	ticker TEXT NOT NULL,
	timeframe VARCHAR(16) NOT NULL,
	setup_family VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	opened_on DATE NOT NULL,
	current_as_of_date DATE NOT NULL,
	last_observed_on DATE NOT NULL,
	closed_on DATE,
	missing_observation_sessions INTEGER DEFAULT '0' NOT NULL,
	current_state VARCHAR(32) NOT NULL,
	current_phase VARCHAR(64) NOT NULL,
	state_entered_on DATE NOT NULL,
	state_age_sessions INTEGER DEFAULT '0' NOT NULL,
	current_actionability VARCHAR(32) NOT NULL,
	confidence_score INTEGER NOT NULL,
	confidence_label VARCHAR(32) NOT NULL,
	opening_snapshot_id BIGINT,
	current_snapshot_id BIGINT,
	closing_snapshot_id BIGINT,
	opening_evaluation_id BIGINT,
	closing_evaluation_id BIGINT,
	terminal_state VARCHAR(32),
	terminal_reason_code TEXT,
	is_primary BOOLEAN DEFAULT 'false' NOT NULL,
	primary_rank INTEGER,
	summary TEXT,
	engine_version TEXT NOT NULL,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(opening_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(current_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(closing_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(opening_evaluation_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(closing_evaluation_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_setup_lifecycle_episodes_current_snapshot ON setup_lifecycle_episodes (current_snapshot_id);""",
    r"""CREATE INDEX idx_setup_lifecycle_episodes_family_state ON setup_lifecycle_episodes (setup_family, current_state);""",
    r"""CREATE INDEX idx_setup_lifecycle_episodes_ticker_status ON setup_lifecycle_episodes (ticker, status);""",
    r"""CREATE UNIQUE INDEX uq_setup_lifecycle_episodes_active_family ON setup_lifecycle_episodes (ticker, timeframe, setup_family) WHERE status = 'ACTIVE';""",
    r"""CREATE TABLE setup_lifecycle_events (
	id BIGSERIAL NOT NULL,
	episode_id BIGINT,
	evaluation_run_id BIGINT,
	snapshot_id BIGINT,
	ticker TEXT NOT NULL,
	timeframe VARCHAR(16) NOT NULL,
	setup_family VARCHAR(32) NOT NULL,
	effective_date DATE NOT NULL,
	event_type VARCHAR(64) NOT NULL,
	from_state VARCHAR(32),
	to_state VARCHAR(32) NOT NULL,
	from_phase VARCHAR(64),
	to_phase VARCHAR(64) NOT NULL,
	state_age_before INTEGER,
	immediate_transition BOOLEAN DEFAULT 'false' NOT NULL,
	actionability_before VARCHAR(32),
	actionability_after VARCHAR(32) NOT NULL,
	confidence_score INTEGER NOT NULL,
	confidence_label VARCHAR(32) NOT NULL,
	severity VARCHAR(32) NOT NULL,
	source_event_key TEXT NOT NULL,
	is_current_version BOOLEAN DEFAULT 'true' NOT NULL,
	superseded_by_event_id BIGINT,
	engine_version TEXT NOT NULL,
	config_version TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	reason_codes_json JSONB DEFAULT '[]' NOT NULL,
	evidence_json JSONB DEFAULT '{}' NOT NULL,
	warning_flags_json JSONB DEFAULT '[]' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_setup_lifecycle_events_eval_source_key UNIQUE (evaluation_run_id, source_event_key),
	FOREIGN KEY(episode_id) REFERENCES setup_lifecycle_episodes (id) ON DELETE SET NULL,
	FOREIGN KEY(evaluation_run_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(superseded_by_event_id) REFERENCES setup_lifecycle_events (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_setup_lifecycle_events_current ON setup_lifecycle_events (is_current_version);""",
    r"""CREATE INDEX idx_setup_lifecycle_events_episode ON setup_lifecycle_events (episode_id);""",
    r"""CREATE INDEX idx_setup_lifecycle_events_ticker_date ON setup_lifecycle_events (ticker, effective_date);""",
    r"""CREATE INDEX idx_setup_lifecycle_events_type ON setup_lifecycle_events (event_type);""",
    r"""CREATE TABLE signal_change_events (
	id BIGSERIAL NOT NULL,
	evaluation_run_id BIGINT,
	episode_id BIGINT,
	previous_snapshot_id BIGINT,
	current_snapshot_id BIGINT,
	ticker TEXT NOT NULL,
	timeframe VARCHAR(16) NOT NULL,
	effective_date DATE NOT NULL,
	category VARCHAR(64) NOT NULL,
	signal_key TEXT NOT NULL,
	value_type VARCHAR(32) NOT NULL,
	old_value_json JSONB DEFAULT '{}' NOT NULL,
	new_value_json JSONB DEFAULT '{}' NOT NULL,
	delta_numeric NUMERIC(18, 8),
	percentage_delta NUMERIC(18, 8),
	percentile_delta NUMERIC(18, 8),
	rank_delta INTEGER,
	normalized_delta NUMERIC(18, 8),
	direction VARCHAR(32) NOT NULL,
	threshold_name TEXT,
	threshold_direction VARCHAR(32),
	severity VARCHAR(32) NOT NULL,
	signal_definition_version TEXT NOT NULL,
	source_event_key TEXT NOT NULL,
	config_hash TEXT NOT NULL,
	reason_codes_json JSONB DEFAULT '[]' NOT NULL,
	evidence_json JSONB DEFAULT '{}' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_signal_change_events_source_key UNIQUE (source_event_key),
	FOREIGN KEY(evaluation_run_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL,
	FOREIGN KEY(episode_id) REFERENCES setup_lifecycle_episodes (id) ON DELETE SET NULL,
	FOREIGN KEY(previous_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL,
	FOREIGN KEY(current_snapshot_id) REFERENCES setup_signal_snapshots (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_signal_change_events_category_severity ON signal_change_events (category, severity);""",
    r"""CREATE INDEX idx_signal_change_events_eval_run ON signal_change_events (evaluation_run_id);""",
    r"""CREATE INDEX idx_signal_change_events_signal ON signal_change_events (signal_key);""",
    r"""CREATE INDEX idx_signal_change_events_ticker_date ON signal_change_events (ticker, effective_date);""",
    r"""CREATE TABLE signal_alert_rules (
	id BIGSERIAL NOT NULL,
	rule_id TEXT NOT NULL,
	enabled BOOLEAN DEFAULT 'true' NOT NULL,
	severity VARCHAR(32) NOT NULL,
	scope VARCHAR(64) NOT NULL,
	setup_family VARCHAR(32),
	cooldown_sessions INTEGER DEFAULT '0' NOT NULL,
	minimum_confidence INTEGER DEFAULT '0' NOT NULL,
	config_version TEXT NOT NULL,
	condition_json JSONB DEFAULT '{}' NOT NULL,
	market_restrictions_json JSONB DEFAULT '{}' NOT NULL,
	metadata_json JSONB DEFAULT '{}' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_signal_alert_rules_rule_id UNIQUE (rule_id)
);""",
    r"""CREATE INDEX idx_signal_alert_rules_enabled_severity ON signal_alert_rules (enabled, severity);""",
    r"""CREATE TABLE signal_alert_events (
	id BIGSERIAL NOT NULL,
	alert_rule_id BIGINT NOT NULL,
	lifecycle_event_id BIGINT,
	signal_change_event_id BIGINT,
	evaluation_run_id BIGINT,
	ticker TEXT NOT NULL,
	timeframe VARCHAR(16) NOT NULL,
	effective_date DATE NOT NULL,
	event_key TEXT NOT NULL,
	source_event_key TEXT NOT NULL,
	status VARCHAR(32) DEFAULT 'UNREAD' NOT NULL,
	severity VARCHAR(32) NOT NULL,
	reason_codes_json JSONB DEFAULT '[]' NOT NULL,
	evidence_json JSONB DEFAULT '{}' NOT NULL,
	acknowledged_at TIMESTAMP WITH TIME ZONE,
	dismissed_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_signal_alert_events_event_key UNIQUE (event_key),
	FOREIGN KEY(alert_rule_id) REFERENCES signal_alert_rules (id) ON DELETE RESTRICT,
	FOREIGN KEY(lifecycle_event_id) REFERENCES setup_lifecycle_events (id) ON DELETE SET NULL,
	FOREIGN KEY(signal_change_event_id) REFERENCES signal_change_events (id) ON DELETE SET NULL,
	FOREIGN KEY(evaluation_run_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_signal_alert_events_rule ON signal_alert_events (alert_rule_id);""",
    r"""CREATE INDEX idx_signal_alert_events_status_severity ON signal_alert_events (status, severity);""",
    r"""CREATE INDEX idx_signal_alert_events_ticker_date ON signal_alert_events (ticker, effective_date);""",
    r"""CREATE TABLE setup_lifecycle_administrative_audit_events (
	id BIGSERIAL NOT NULL,
	event_type VARCHAR(64) NOT NULL,
	evaluation_run_id BIGINT,
	requester TEXT NOT NULL,
	reason TEXT,
	preview_token_hash TEXT,
	scope_json JSONB DEFAULT '{}' NOT NULL,
	before_json JSONB DEFAULT '{}' NOT NULL,
	after_json JSONB DEFAULT '{}' NOT NULL,
	affected_counts_json JSONB DEFAULT '{}' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(evaluation_run_id) REFERENCES setup_lifecycle_evaluation_runs (id) ON DELETE SET NULL
);""",
    r"""CREATE INDEX idx_setup_lifecycle_admin_audit_created ON setup_lifecycle_administrative_audit_events (created_at);""",
    r"""CREATE INDEX idx_setup_lifecycle_admin_audit_eval ON setup_lifecycle_administrative_audit_events (evaluation_run_id);""",
    r"""CREATE INDEX idx_setup_lifecycle_admin_audit_type ON setup_lifecycle_administrative_audit_events (event_type);""",
)


def upgrade() -> None:
    for statement in CREATE_TABLE_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("setup_lifecycle_administrative_audit_events")
    op.drop_table("signal_alert_events")
    op.drop_table("signal_alert_rules")
    op.drop_table("signal_change_events")
    op.drop_table("setup_lifecycle_events")
    op.drop_table("setup_lifecycle_episodes")
    op.drop_table("setup_signal_snapshots")
    op.drop_table("setup_lifecycle_evaluation_runs")
