from __future__ import annotations

SLSE_PIPELINE_CAPTURE_STEP = "CAPTURING_SETUP_SIGNALS"
SLSE_PIPELINE_EVALUATION_STEP = "EVALUATING_SETUP_LIFECYCLES"
SLSE_PIPELINE_STEPS = (
    SLSE_PIPELINE_CAPTURE_STEP,
    SLSE_PIPELINE_EVALUATION_STEP,
)

SLSE_API_ERROR_CODES = frozenset(
    {
        "INVALID_STATE",
        "INVALID_DATE",
        "INVALID_THRESHOLD",
        "INVALID_SORT",
        "INVALID_CURSOR",
        "INVALID_CONFIGURATION",
        "TICKER_NOT_FOUND",
        "EPISODE_NOT_FOUND",
        "EVALUATION_NOT_FOUND",
        "ALERT_NOT_FOUND",
        "RUN_LIFECYCLE_NOT_FOUND",
    }
)

SLSE_ADMIN_EVALUATION_SCOPES = (
    "source_run",
    "ticker",
    "date_range",
    "all_eligible",
)
SLSE_ADMIN_EVALUATION_MODES = (
    "capture_only",
    "evaluate",
    "dry_run",
    "replay",
    "repair",
)

SLSE_TRIGGER_AUTHORITY = "COMPLETED_DAILY_CLOSE"
SLSE_ORIGIN_MODE = "LIVE_FORWARD_CAPTURE"
SLSE_RUN_DELETION_POLICY = "SET_NULL_WITH_IMMUTABLE_SOURCE_IDENTITY"

SLSE_REPLAY_OUTPUT_AUTHORITATIVE_BY_DEFAULT = False
SLSE_REPLAY_PROMOTION_REQUIRES_EXPLICIT_ADMIN_ACTION = True
SLSE_RETAIN_IMMUTABLE_EVIDENCE_INDEFINITELY = True
SLSE_RECONSTRUCTED_EXCLUDED_FROM_LIVE_ALERTS_BY_DEFAULT = True
SLSE_RECONSTRUCTED_EXCLUDED_FROM_OWPE_EXPORT_BY_DEFAULT = True

SLSE_CAPTURE_EVALUATION_TARGET_SECONDS = 60
SLSE_API_P95_TARGET_MS = 500
SLSE_PERFORMANCE_FIXTURE_MIN_SNAPSHOTS = 100_000
