from __future__ import annotations

CERI_PIPELINE_CAPTURE_STEP = "CERI_CAPTURE_SNAPSHOT"
CERI_PIPELINE_PROVIDER_INGEST_STEP = "CERI_PROVIDER_INGEST"
CERI_PIPELINE_STEPS = (CERI_PIPELINE_CAPTURE_STEP,)

CERI_API_ERROR_CODES = frozenset(
    {
        "INVALID_FILTER",
        "INVALID_DATE_RANGE",
        "INVALID_SORT",
        "INVALID_CURSOR",
        "INVALID_CONFIGURATION",
        "TICKER_NOT_FOUND",
        "RUN_NOT_FOUND",
        "PROVIDER_CAPABILITY_UNAVAILABLE",
        "CONFIG_VERSION_NOT_FOUND",
        "REVIEW_CONFLICT",
        "BACKFILL_ALREADY_ACTIVE",
        "LICENSE_RESTRICTED",
        "PURGE_CONFIRMATION_REQUIRED",
        "ADMIN_FORBIDDEN",
        "DUPLICATE_ACTIVE_BACKFILL",
        "LICENSE_RESTRICTED_FIELD",
        "PURGE_CONFLICT",
        "UNAUTHORIZED_LOCAL_ADMIN",
    }
)

CERI_DAILY_CUTOFF_TIMEZONE = "America/New_York"
CERI_EFFECTIVE_SESSION_POLICY = "AFTER_HOURS_NEXT_COMPLETED_US_SESSION"
CERI_SOURCE_CONFLICT_POLICY = "PROVIDER_PRIORITY_PRESERVE_ALL_OBSERVATIONS"
CERI_RUN_DELETION_POLICY = "SET_NULL_RETAIN_IMMUTABLE_EVIDENCE"

CERI_LOCAL_ADMIN_REQUIRED = True
CERI_ADMIN_CSRF_REQUIRED = True
CERI_ORDER_PLACEMENT_ALLOWED = False

CERI_JOB_REQUEST_KEYS_REQUIRED = True
CERI_JOB_EXECUTION_FENCING_REQUIRED = True
CERI_JOB_HEARTBEATS_REQUIRED = True
CERI_JOB_CHECKPOINTS_REQUIRED = True

CERI_LICENSED_PURGE_REQUIRES_PREVIEW = True
CERI_LICENSED_PURGE_REQUIRES_CONFIRMATION = True
CERI_LICENSED_PURGE_REQUIRES_AUDIT = True
