from enum import StrEnum


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    SUBSCRIPTION_REQUIRED = "SUBSCRIPTION_REQUIRED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    STALE = "STALE"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class IntelligenceModule(StrEnum):
    LIQUIDITY = "LIQUIDITY"
    SHORT_PRESSURE = "SHORT_PRESSURE"
    VOLATILITY = "VOLATILITY"
    OPTIONS_ACTIVITY = "OPTIONS_ACTIVITY"
    SCANNER = "SCANNER"
    HISTOGRAM = "HISTOGRAM"
    FLEX = "FLEX"


class HistoricalMetricType(StrEnum):
    BID_ASK = "BID_ASK"
    FEE_RATE = "FEE_RATE"
    HISTORICAL_VOLATILITY = "HISTORICAL_VOLATILITY"
    OPTION_IMPLIED_VOLATILITY = "OPTION_IMPLIED_VOLATILITY"


HISTORICAL_METRIC_SEMANTICS = {
    HistoricalMetricType.BID_ASK: "TIME_AVERAGE_BID_ASK",
    HistoricalMetricType.FEE_RATE: "BORROW_FEE_RATE",
    HistoricalMetricType.HISTORICAL_VOLATILITY: "HISTORICAL_VOLATILITY_RATE",
    HistoricalMetricType.OPTION_IMPLIED_VOLATILITY: "OPTION_IMPLIED_VOLATILITY_RATE",
}


class RunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Confidence(StrEnum):
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"
